server:
  port: 9003
  error:
    include-stacktrace: never

spring:
  application:
    name: transaction-service
  profiles.active: local
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: postgres
    password: postgres
#  cloud:
#    config:
#      enabled: false