server:
  port: 9002
# error:
#   include-stacktrace: never
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: account-service
  profiles.active: local
# sql:
#   init:
#      platform: 
  datasource:
    url: jdbc:mysql://localhost:3306/bankapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: NON_NULL
  mvc:
    converters:
      preferred-json-mapper: jackson

logging:
  level:
    org:
      hibernate:
        SQL: error
        type: error
      springframework:
        web: error
        security: DEBUG
    root: error

#  cloud:
#    config:
#      enabled: false
